### ISSUE TITLE
checksum error

### ISSUE THREAD

**Issue by QuadmanSWE** [marcinbojko/ssrs#3]
when using choco install ssrs the new version of the exe is downloaded but the checksum is compared for .1109.

**Comment by QuadmanSWE** [comment]
from powershell:
Progress: 100% - Completed download of C:\ProgramData\choco-cache\ssrs\14.0.600.1109\SQLServerReportingServices.exe (95.6 MB).
Download of SQLServerReportingServices.exe (95.6 MB) completed.
Error - hashes do not match. Actual value was 'BD0C482A4B0F381388CE512E7E38CD5E466B9E8945EBC632D0D3B0B2A8A2AA3A'.
ERROR: Checksum for 'C:\ProgramData\choco-cache\ssrs\14.0.600.1109\SQLServerReportingServices.exe' did not meet '99aaffce8a003839e69e4fad8bcbbc3a71d946902f876df421210dbb7
aa6a3c7' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less se
cure option is to pass --ignore-checksums if necessary.
The install of ssrs was NOT successful.

**Comment by marcinbojko** [comment]
Our lovely Microsoft.
New version was pushed yesterday to chocolatey.

**Comment by QuadmanSWE** [comment]
ok thanks. its my fault that i dont save the packages locally and distribute them to my testing environments but download them from the source every time. Thanks for quick answer!

**Comment by marcinbojko** [comment]
No worries. Unfortunatelly MS doesn't change paths for downloads, so archival version are not available easy. 
Saving packages locally (without rebuilding nupkg) won't help you ;(
For test feel free to use my dev repository

https://www.myget.org/feed/public-choco-dev/package/nuget/ssrs

choco install ssrs --version 14.0.600.1274 --source https://www.myget.org/F/public-choco-dev/api/v2

**Comment by marcinbojko** [comment]
Done, package is visible.
