### ISSUE TITLE
Shouldn't there be a new release and tag for 14.0.600.1274?

### ISSUE THREAD

**Issue by abousias** [marcinbojko/ssrs#4]
@marcinbojko I see the chocolatey package has been submitted, but the version is mentioned in this repo. I suggest you make a new `pre-release` and when it gets approved you mark it as released 😄

**Comment by marcinbojko** [comment]
Hi, I am not pushing to this repo/master until it gets approved.
I hope that doesn't bother you much ;)

**Comment by abousias** [comment]
No worries I just saw that the tag is not moved, so we're good. The release
says that it has been updated but most probably it only checks on the
default branch ;)
